### ISSUE TITLE
Cloning doesn't work in certain circumstances

### ISSUE THREAD

**Issue by linuxgurugamer** [Nereid42/S.A.V.E#3]
I found that the clone function is not working in certain circumstances. One which I was able to isolate:

Start game after fresh install, create game, do single save, then clone.  clone directory is created, but nothing done.  I saw that the file GameData/S.A.V.E.dat was not created at this time

**Comment by linuxgurugamer** [comment]
Closing since it seems to be working

**Comment by Nereid42** [comment]
Just to be sure: So anything is working under 1.10?

 

 




Gesendet: Donnerstag, 02. Juli 2020 um 00:29 Uhr
Von: "linuxgurugamer" <notifications@github.com>
An: "Nereid42/S.A.V.E" <S.A.V.E@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: Re: [Nereid42/S.A.V.E] Cloning doesn't work in certain circumstances (#3)


 

Closed #3.

**Comment by linuxgurugamer** [comment]
I did a test and the clone seemed to work.  It wasn't exhaustive, I suspect that whatever was going on was fixed in an update.  I'll do more test and let you know if anything else is noticed

**Comment by Nereid42** [comment]
Thanks. I will try to release an upddate for 1.1.0 this weekend for all mods anyway.


 

Gesendet: Donnerstag, 02. Juli 2020 um 22:03 Uhr
Von: "linuxgurugamer" <notifications@github.com>
An: "Nereid42/S.A.V.E" <S.A.V.E@noreply.github.com>
Cc: "Nereid" <ako42@gmx.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [Nereid42/S.A.V.E] Cloning doesn't work in certain circumstances (#3)


 

I did a test and the clone seemed to work. It wasn't exhaustive, I suspect that whatever was going on was fixed in an update. I'll do more test and let you know if anything else is noticed

**Comment by linuxgurugamer** [comment]
You should look at the thread on the forum.  There is a problem with the threading, when it tries to write logs?  Crashes games.  I have a local verison in which I replaced the threading with coroutines, could send them to you along with a few other fixes.  @Lisias claims he will be submitting a PR to fix the threading issue, nothing from him yet
